#!/bin/bash
say () {
  # espeak "$1" -p 20 -s 140 >/dev/null 2>/dev/null
  echo '(SayText "'"`echo "$1" | sed 's/["\\]//g'`"'")' | aoss festival
}

format='[[%artist% - ]%title%]|[!path!%file%]'
filter='s|^!path!.*/||; s|\.[a-zA-Z0-9]{2,4}$||; s|_| |g'

lastsong="`mpc current -f "$format" | perl -pe "$filter"`"
while true; do
  song="`mpc current -f "$format" --wait | perl -pe "$filter"`"
  mpc pause >/dev/null
  say "$lastsong"
  say "$song"
  lastsong="$song"
  mpc play >/dev/null
done
